### ISSUE TITLE
percent < 0

### ISSUE THREAD

**Issue by bradintheusa** [diegoveloper/flutter_percent_indicator#1]
setting percent < 0.0 is a bad idea but I think the control should display an empty progress bar not an error.

**Comment by diegoveloper** [comment]
It depends on how you see it, if it's an incorrect value it is best to display an error, otherwise the developer won't know why it does not display anything.
But I will leave this issue open to see if others require it.
Thanks

**Comment by bradintheusa** [comment]
BTW: It's in production now.  The screenshots in the store have not been updated but the app is using the component.  Thanks For You work..

https://play.google.com/store/apps/details?id=com.scrbrd.playcounter2

**Comment by diegoveloper** [comment]
Awesome !!!
