### ISSUE TITLE
start angle and End angle

### ISSUE THREAD

**Issue by maheshmnj** [diegoveloper/flutter_percent_indicator#10]
How can I add a start angle and the end angle  for the Circular percent chart

**Comment by diegoveloper** [comment]
Hello, it is not implemented yet. I will add this for the next release or you can for the project and send a pull request :)

**Comment by maheshmnj** [comment]
Well I am not familiar How to do that but I will try my best thanks for the reply by the way

**Comment by diegoveloper** [comment]
startAngle was added on version percent_indicator: ^1.0.11

**Comment by maheshmnj** [comment]
thanks diegoveloper can you suggest some resource to learn building these cool widgets
