### ISSUE TITLE
compatible with expanded or radius infinity

### ISSUE THREAD

**Issue by Hwan-seok** [diegoveloper/flutter_percent_indicator#101]
## Problem
Sometime we have to determine indicator's width from double.infinite or max space available.
But it have required property named `radius`

## Question
How can i make it to have max space available?

**Comment by diegoveloper** [comment]
hmm can you try using LayoutBuilder as a parent and get the size from there.

**Comment by Hwan-seok** [comment]
@diegoveloper 
Oh... god excuse my ignorance. Thanks, it works!
