### ISSUE TITLE
Linear progress animation not showing

### ISSUE THREAD

**Issue by Atikur-Rahman-Sabuj** [diegoveloper/flutter_percent_indicator#103]
@diegoveloper Thanks for the amazing package.  For LinearPercentIndicator when I changing the percent value animation is showing from beginning not for only the progress.
My implementation

    `import 'package:flutter/cupertino.dart';
    import 'package:flutter/material.dart';
    import 'package:percent_indicator/linear_percent_indicator.dart';
    
    class MyProgressIndicator extends StatelessWidget {
      final int total;
      final int progress;
    
      const MyProgressIndicator({Key key, this.total, this.progress})
          : super(key: key);
    
      @override
      Widget build(BuildContext context) {
        return LinearPercentIndicator(
          percent: progress / total,
          lineHeight: 20.0,
          progressColor: Colors.blue,
          linearStrokeCap: LinearStrokeCap.roundAll,
          animation: true,
          animationDuration: 1000,
          center: Text(progress.toString() + "/" + total.toString()),
        );
      }
    }`

**Comment by diegoveloper** [comment]
Hello, did you try using the `animateFromLastPercent` as `true` ?

**Comment by Atikur-Rahman-Sabuj** [comment]
It's working with animateFromLastPercent as true. Sorry unfortunately I did not see that property.
