### ISSUE TITLE
there's a grey stroke around the LinearPercentIndicator

### ISSUE THREAD

**Issue by Hasankanso** [diegoveloper/flutter_percent_indicator#104]
thank you for sharing such a good work.
I have a problem with LinearPrecentIndicator, I use this code:
```
            LinearPercentIndicator(
              width: 140.0,
              lineHeight: 15.0,
              percent: 100,
              center: Text(
                "100%",
 ),
              backgroundColor: Colors.red,
              progressColor: Colors.green,
            )
```

![Screenshot from 2021-01-21 02-07-41](https://user-images.githubusercontent.com/42151674/105260267-ce06ca80-5b8d-11eb-924e-ba3bf4785c72.png)

I can see a grey or a red color on the right side of the indicator. can this be fixed?

**Comment by diegoveloper** [comment]
hmm maybe it's something related to this bug-> https://github.com/flutter/flutter/issues/14288
