### ISSUE TITLE
Unwanted lineWidth added to CircularPercentIndicator height

### ISSUE THREAD

**Issue by olof-dev** [diegoveloper/flutter_percent_indicator#105]
This is a great package, thanks for making it!

I noticed that the height of a CircularProgressIndicator I was using is slightly off, compared to its surroundings, and it is because `lineWidth` is hardcoded into being added to the widget's height (but not width):

https://github.com/diegoveloper/flutter_percent_indicator/blob/44e46d555a7188159270924a4ace92ea5a4c6958/lib/circular_percent_indicator.dart#L232-L233

I don't quite understand why that `+ lineWidth` is there for height but not width. Can we get rid of it, or make it the same for both height and width, or is there something non-obvious going on?

**Comment by br-programmer** [comment]
Hi, nice catch I'll take a look at this and let you know.

**Comment by diegoveloper** [comment]
thanks @br-programmer , @olof-dev new version is ready , let me know if this fixes the bug. https://pub.dev/packages/percent_indicator/versions/2.1.9+1

**Comment by olof-dev** [comment]
@diegoveloper Yupp that does it. Thanks to you and @br-programmer for the quick turnaround!
