### ISSUE TITLE
LinearPercentIndicator width 100%

### ISSUE THREAD

**Issue by mdmota** [diegoveloper/flutter_percent_indicator#108]
How to define the LinearPercentIndicator with width 100% in relation to the container in which it is inserted?

**Comment by diegoveloper** [comment]
Did you try with `Container` + `LayoutBuilder` ? in layout builder you can get the `constraints`.

**Comment by mdmota** [comment]
Can you give me an example?

**Comment by diegoveloper** [comment]
https://api.flutter.dev/flutter/widgets/LayoutBuilder-class.html

**Comment by ali9653** [comment]
> How to define the LinearPercentIndicator with width 100% in relation to the container in which it is inserted?

if you were successful in achieving this can you please share your code?

**Comment by GuilhermeDemoliner** [comment]
You can put LinearPercentIndicator inside a row with flexible.
` Row(
      children:[
           Flexible(
               child: LinearPercentIndicator()
           )
    ])
`
