### ISSUE TITLE
I can´t use it, error at import

### ISSUE THREAD

**Issue by rimedar** [diegoveloper/flutter_percent_indicator#109]
Hi, when i import the library `import 'package:percent_indicator/percent_indicator.dart';` flutter show this error 

`
Compiler message:
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/percent_indicator-2.1.9+1/lib/linear_percent_indicator.dart:235:9: Error: No named parameter with the name 'clipBehavior'.
        clipBehavior: Clip.none,
        ^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/basic.dart:3210:3: Context: Found this candidate, but the arguments don't match.
  Stack({
  ^^^^^
`

How i can fix it? thanks.

**Comment by diegoveloper** [comment]
Update your flutter version
