### ISSUE TITLE
RTL orientation 

### ISSUE THREAD

**Issue by ahmednet0001** [diegoveloper/flutter_percent_indicator#11]
Hi 
Thanks very much for this package.
My problem is that I want the tape to appear from right to left.
Although I use Directionality widget 
It did not work
![isuss](https://user-images.githubusercontent.com/11617821/50368700-6045da00-0594-11e9-8ecc-8677518517be.png)

**Comment by diegoveloper** [comment]
Just change the progressColor and backgroundColor

**Comment by ahmednet0001** [comment]
But as percent increases it will move from left to right

**Comment by diegoveloper** [comment]
1.0 - your_percent_value

**Comment by ahmednet0001** [comment]
Exception  when using negative percent  
![screenshot_1545440995](https://user-images.githubusercontent.com/11617821/50368972-2cb87f00-0597-11e9-9878-36e17c9c3728.png)

**Comment by diegoveloper** [comment]
Your_percent_value must not be greater than 1.0.

1.0 - your_percent_value  will never be negative.

**Comment by ahmednet0001** [comment]
OK I know that , but what I change to make it  RTL  orientation

**Comment by diegoveloper** [comment]
Change colors. Background with progressColor and  change the value  to :
(1.0  - your_percent-value) what is the result of that change?
Post code and result image.

**Comment by diegoveloper** [comment]
If you set:  percent: 1.0 - your_percent_value  is not static.

**Comment by ahmednet0001** [comment]
Ok anyway thank you "diegoveloper 
![isuss](https://user-images.githubusercontent.com/11617821/50369216-47d8be00-059a-11e9-81e6-6d6cdb815e00.png)
"I solve it using Transform.rotate

**Comment by diegoveloper** [comment]
Nice :)
