### ISSUE TITLE
Feature add linear gradient to background color

### ISSUE THREAD

**Issue by jeremiahlukus** [diegoveloper/flutter_percent_indicator#113]
Would you be open if i made this PR?  I need to do this for a project i am working on

**Comment by diegoveloper** [comment]
For sure, PRs are welcome

**Comment by jeremiahlukus** [comment]
Sweet working on it now ill send a PR soon

**Comment by jeremiahlukus** [comment]
https://github.com/diegoveloper/flutter_percent_indicator/pull/114

**Comment by jeremiahlukus** [comment]
merged
