### ISSUE TITLE
Animation does not work for ongoing tasks

### ISSUE THREAD

**Issue by shinayser** [diegoveloper/flutter_percent_indicator#12]
Hey! First of all thanks for such great library. I use it a lot!
But one issue I have is to show a ongoing task progress indication, like a download progress.
If I set the **animation** to **true**, it always animate from 0 to the current progress, instead of animating the latest progress value to the current.

Thanks a lot!

**Comment by diegoveloper** [comment]
Hello, I made some changes, could you try using the url of my repo?

```
percent_indicator:
    git: https://github.com/diegoveloper/percent_indicator 
```
And set this flag to the LinearPercentIndicator 

```
animateFromLastPercent: true,
```

**Comment by shinayser** [comment]
Hey man, nope it didin't work. I believe you forgot to update the "lastPercent" after the animation is finished or something like that.
Also,  was using the CircularPercentIndicator. Hope this changes are easy to port into it :)

best regards!

**Comment by diegoveloper** [comment]
How are you tested it?  It tested using a percent of 0.2 , then I updated the widget and update the percent to 0.9, and the progress move from 0.2 to 0.9 . 
Could you show me the code you are using and tell me what is not working ?

**Comment by shinayser** [comment]
I am using a StreamBuilder listening for a stream of values (the current progress).
Every iteration I set the CircularPercentIndicator to the current value. It animates, but not from the last value but also not from 0 (as before your update). Pretty weird =P

**Comment by diegoveloper** [comment]
Oh ok, but that change was only for LinearPercentIndicator adding the property 'animateFromLastPercent' true.

**Comment by shinayser** [comment]
Check this snipper:

```
import 'package:flutter/material.dart';
import 'package:percent_indicator/linear_percent_indicator.dart';
import 'package:rxdart/rxdart.dart';

class IndicatorTest extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var observable = Observable.periodic(Duration(milliseconds: 1500), (value) => value * value);

    return StreamBuilder(
      stream: observable,
      initialData: 0,
      builder: (BuildContext context, AsyncSnapshot<int> snapshot) {
        return Center(
          child: LinearPercentIndicator(
            width: 300,
            percent: snapshot.data.toDouble() / 100,
            animation: true,
            animateFromLastPercent: true,
          ),
        );
      },
    );
  }
}
```

**Comment by diegoveloper** [comment]
is not working for you?  I tested your code and it's working fine, I just have to add a validation.

```
 return StreamBuilder(
      stream: observable,
      initialData: 0,
      builder: (BuildContext context, AsyncSnapshot<int> snapshot) {
        double value = snapshot.data.toDouble() / 100;
        if (value > 1.0) {
          value = 1.0;
        }
        return Center(
          child: LinearPercentIndicator(
            width: 300,
            percent: value,
            animation: true,
            animateFromLastPercent: true,
          ),
        );
      },
    );
```

**Comment by shinayser** [comment]
Check this gif:

![library bug](https://user-images.githubusercontent.com/1146982/50651282-010ba080-0f6a-11e9-8df2-f457ba87a0f4.gif)

This is the code I am running:

```
class IndicatorTest extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var observable = Observable.periodic(Duration(milliseconds: 500), (value) => value);

    return StreamBuilder(
      stream: observable,
      initialData: 0,
      builder: (BuildContext context, AsyncSnapshot<int> snapshot) {
        return Center(
          child: LinearPercentIndicator(
            width: 300,
            percent: math.min(snapshot.data.toDouble() / 100, 1),
            animation: true,
            animateFromLastPercent: true,
          ),
        );
      },
    );
  }
}
```

**Comment by diegoveloper** [comment]
Ok, acabo de actualizar el código, puedes probar nuevamente?  tienes que bajar las dependencies de nuevo :  flutter packages get

**Comment by shinayser** [comment]
IT WORKS! Nice job man! Is it possible now to port ths changes into the Circular indicator?

**Comment by diegoveloper** [comment]
Yes, give me some time. I'm busy now. I'll let you know when it is ready
today.

**Comment by shinayser** [comment]
Thanks bro, you done a great job here. Best regards!

**Comment by diegoveloper** [comment]
Could you try again with CircularPercentIndicator? the same property as Linear .. let me know if it works.

**Comment by shinayser** [comment]
Worked! Nice job again bro. When you will be publishing it on PUB ?

**Comment by shinayser** [comment]
Actually it worked for the animation: true but not working for animation: false. Or I am wrong?

**Comment by diegoveloper** [comment]
It should work only when the animation is true.  
If you could help me testing different scenarios I'll publish it today.

**Comment by shinayser** [comment]
Just tested again, seems ok to me now! Cirular and Linear are working in both cases, animated and not animated! 👍

**Comment by diegoveloper** [comment]
Done, you could try using this version :  1.0.12

**Comment by ganisback** [comment]
great job @diegoveloper, it works for me
