### ISSUE TITLE
Android: When used on a stack on top of a circle-shape container, the CirclePercentIndicator widget is not rendered properly.

### ISSUE THREAD

**Issue by nebooz** [diegoveloper/flutter_percent_indicator#13]
It works completely fine on the iOS simulator, but there is something weird happening while using the Circle Percent Indicator in a Stack widget on top of a container also made to look like a circle using BoxShape.

What is even weirder is that when Debug Paint is on, it looks properly rendered.

I think the images make it clear.

![image](https://user-images.githubusercontent.com/7244289/51445347-be133200-1cb8-11e9-8ccf-bd28cf970bbd.png)

![image](https://user-images.githubusercontent.com/7244289/51445359-dd11c400-1cb8-11e9-94e8-a5c0778f2f5b.png)

```dart
Stack(
  alignment: AlignmentDirectional.center,
  children: <Widget>[
    Container(
      width: 44.0,
      height: 40.0,
      color: Colors.grey[700],
    ),
    Container(
      width: 36.0,
      height: 36.0,
      decoration: BoxDecoration(
        color: Colors.black,
        borderRadius: BorderRadius.circular(18),
      ),
    ),
    Container(
      alignment: Alignment.center,
      //color: Colors.transparent,
      height: 34.0,
      width: 34.0,
      child: CircularPercentIndicator(
        radius: 30.0,
        lineWidth: 4.0,
        animation: true,
        animationDuration: 1000,
        percent: movies[index].voteAverage / 10,
        center: Row(
          crossAxisAlignment:
              CrossAxisAlignment.center,
          mainAxisAlignment:
              MainAxisAlignment.center,
          children: <Widget>[
            Text(
              (((movies[index].voteAverage) * 10)
                  .toStringAsFixed(0)),
              style: TextStyle(
                  fontSize: 11.0,
                  color: Colors.white,
                  fontWeight: FontWeight.bold),
            ),
            Text(
              "%",
              style: TextStyle(
                  color: Colors.white,
                  fontWeight: FontWeight.bold,
                  fontSize: 6.0),
            )
          ],
        ),
        circularStrokeCap:
            CircularStrokeCap.round,
        progressColor: progressColor,
        backgroundColor: progressColor.shade900,
      ),
    ),
  ],
)

**Comment by nebooz** [comment]
Hi. This is what I'm running:
*Flutter (Channel beta, v1.0.0, on Mac OS X 10.13.6 17G65, locale en-US)*

And the emulator:
*Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)*

**Comment by diegoveloper** [comment]
Try changing to 'stable' version.

run :  flutter channel stable

**Comment by nebooz** [comment]
I changed to stable and the issue remains. Just for fun, I tried running it on Android Pie and same thing. Anything else I might try?

**Comment by diegoveloper** [comment]
Could you add a screenshot to check how it looks like? Also add the flutter
doctor log here.

**Comment by nebooz** [comment]
That fixed it. Wonder what was the issue... guess I'll stay in the dev channel from now on. Thanks! 👍 

![image](https://user-images.githubusercontent.com/7244289/51447245-f6266f00-1cd0-11e9-86b5-f1790bc8b753.png)
