### ISSUE TITLE
CircularPercentIndicator change colors of the center

### ISSUE THREAD

**Issue by robpot95** [diegoveloper/flutter_percent_indicator#131]
Hello,

i would like to change the color of the center, same as the background color of the circle. 

How it is now:
![image](https://user-images.githubusercontent.com/34423774/141017773-a3f91ec2-703d-46ee-95f1-f4e49d32808b.png)

What i would like to achive:
![image](https://user-images.githubusercontent.com/34423774/141017974-667abadb-f439-4f07-9389-23f8c4149194.png)

**Comment by diegoveloper** [comment]
add a minimum sample code to reproduce the issue.

**Comment by robpot95** [comment]
Well it's not a issue, i wonder if it's possible to change color around inside the circle as the toilet image. I seem not find it possible at the moment

**Comment by moxran** [comment]
You can wrap it in a container:
Container(
                height: percentIndicatorRadius*2,
                decoration: BoxDecoration(
                  color: shadingColor,
                  shape: BoxShape.circle,
                ),
               child: CircularPercenIndicator(
               radius: percentIndicatorRadius
               ......
               )
)
