### ISSUE TITLE
Disruption lifecycle child of PageView that uses CircularPercentIndicator

### ISSUE THREAD

**Issue by Chakib-Temal** [diegoveloper/flutter_percent_indicator#135]
Hi 
I have a PageView which uses 8 Widgets

the widget that uses CircularPercentIndicator never dies, so when I jump to other pages and come back to the page where there is CircularPercentIndicator, initState is not executed again

when i remove CircularPercentIndicator from this Widget, the problem disappears

my widget don't use "with AutomaticKeepAliveClientMixin"

**Comment by diegoveloper** [comment]
https://github.com/diegoveloper/flutter_percent_indicator/blob/master/lib/circular_percent_indicator.dart#L76
