### ISSUE TITLE
progressColor not show in 4.0.0 version

### ISSUE THREAD

**Issue by Hendriyawan** [diegoveloper/flutter_percent_indicator#143]
Hi, please correct me, what wrong with my code, the progressColor is not working

LinearPercentIndicator(
                    width: MediaQuery.of(context).size.width / 2 * 1.1,
                    animation: true,
                    animationDuration: 1000,
                    lineHeight: 17,
                    center: Text(
                      (widget.course.percent * 100).toString() + "%",
                      style: GoogleFonts.montserrat(
                        color: Colors.black45,
                      ),
                    ),
                    backgroundColor: Colors.grey[200],
                    progressColor: Colors.blue,
                    // ignore: deprecated_member_use
                    barRadius: const Radius.circular(20),
                  ),

**Comment by diegoveloper** [comment]
What's the percent value?

**Comment by Hendriyawan** [comment]
hi, percenet is double

**Comment by Hendriyawan** [comment]
ah, solved, sorry, i forgot to call percent property, thank you
