### ISSUE TITLE
LinearStrokeCap is deprecated

### ISSUE THREAD

**Issue by dhanrajdc7** [diegoveloper/flutter_percent_indicator#144]
# Issue
Unable to achieve rounded borders to Linear Percent Indicator in latest version of Dart & Flutter

# Error
'LinearStrokeCap' is deprecated and shouldn't be used. This property is no longer used, please use barRadius instead.

# Screenshot
![Screenshot 2022-02-03 at 11 52 38](https://user-images.githubusercontent.com/39642060/152292055-0a578a3f-9bce-47a2-b5d0-db850456c8b1.png)

**Comment by diegoveloper** [comment]
https://github.com/diegoveloper/flutter_percent_indicator/blob/master/example/lib/sample_linear_page.dart#L139

**Comment by dhanrajdc7** [comment]
Thank you.
