### ISSUE TITLE
Getting error in linear percent indicator

### ISSUE THREAD

**Issue by thechawla225** [diegoveloper/flutter_percent_indicator#145]
![image](https://user-images.githubusercontent.com/45570514/152741014-b692789a-bb11-470b-bd26-f4394507caa2.png)

Flutter version: 
![image](https://user-images.githubusercontent.com/45570514/152741139-b7921a56-d8dc-40ef-a248-efade1f573a1.png)

Code: 
```
LinearPercentIndicator(
                width: 140.0,
                lineHeight: 14.0,
                percent: 0.5,
                backgroundColor: Colors.grey,
                progressColor: Colors.blue,
              ),

```

**Comment by diegoveloper** [comment]
Try on flutter stable channel

**Comment by thechawla225** [comment]
@diegoveloper yeah I switched to stable channel and ran flutter upgrade, no error now, thanks
