### ISSUE TITLE
WidgetsBinding.instance?.addPostFrameCallback((_) {

### ISSUE THREAD

**Issue by haleem13** [diegoveloper/flutter_percent_indicator#146]
hi there,
i am facing this problem can you please help me to fix this.
Error
/[C:/flutter/.pub-cache/hosted/pub.dartlang.org/percent_indicator-3.4.0/lib/linear_percent_indicator.dart:156:20](): Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/[C:/flutter/packages/flutter/lib/src/widgets/binding.dart]()').
package:flutter/…/widgets/binding.dart:1
    WidgetsBinding.instance?.addPostFrameCallback((_) {
                           ^

**Comment by diegoveloper** [comment]
run flutter doctor, which version of Flutter?
