### ISSUE TITLE
1% progress should be inside.

### ISSUE THREAD

**Issue by flomingdev** [diegoveloper/flutter_percent_indicator#147]
![Screenshot 2022-03-16 at 10 46 40 PM](https://user-images.githubusercontent.com/72783084/158649316-8dc92d58-4040-49c3-919a-659e152893be.png)
The progress should be inside the linear bar.
How can we resolve this kind of problem? Does anyone have some workaround solutions?
Thanks!

**Comment by xlDownxl** [comment]
Same problem here.

**Comment by diegoveloper** [comment]
Can anyone add a minimum code to reproduce the issue?

**Comment by xlDownxl** [comment]
Here is a static example to reproduce:
`LinearPercentIndicator(
      width: 150.0,
      lineHeight: 20.0,
      barRadius: Radius.circular(10),
      percent: 0.05,
      clipLinearGradient: true,
    )`

As soon as the percentage goes very low (eg. 0.05 here), the progress bar behaves like shown in the first post.

Thanks for taking on the issue!

**Comment by diegoveloper** [comment]
Can you add a complete minimum example that I can run here?

**Comment by xlDownxl** [comment]
I figured out that the problem comes from the barRadius parameter: If the progress bar itself is too small to fit the rounded corner radius, the bar will be displayed erronous.

**Comment by diegoveloper** [comment]
> I figured out that the problem comes from the barRadius parameter: If the progress bar itself is too small to fit the rounded corner radius, the bar will be displayed erronous.

@xlDownxl do you want to send a pull request?

**Comment by xlDownxl** [comment]
@diegoveloper I only located the problem, I don't have a fix for it. Personally, I am not so familiar with the Drawer, so I am not sure if I can find a solution to this problem soon.

**Comment by daveleenew** [comment]
Same problem here.

**Comment by diegoveloper** [comment]
please add a complete minimum example that I can run here

**Comment by deakjahn** [comment]
@diegoveloper Diego, really no need for an example. Just set your bar in your own example to 1 percent.

![Small-values](https://user-images.githubusercontent.com/2234271/166926426-52177847-6cd9-45e6-8265-745317ec25e5.png)

Here's another image. If the percentage value is low, the bar will be drawn outside the background.

**Comment by deakjahn** [comment]
See https://github.com/diegoveloper/flutter_percent_indicator/pull/154.
