### ISSUE TITLE
Change the border radius

### ISSUE THREAD

**Issue by LaTrita97** [diegoveloper/flutter_percent_indicator#148]
It is possible to change the border radius of the percent indicator?

Now we can only select from `.butt` and `.round` but if I would add to the corners a radius of `5.0` I can't.

Could you add this feature or not?

Best regards.

**Comment by diegoveloper** [comment]
https://github.com/diegoveloper/flutter_percent_indicator/blob/6e30d8d3bad25db72803375eb9f0ae13de95cfed/lib/linear_percent_indicator.dart#L49

**Comment by LaTrita97** [comment]
Thank you👍🏻
