### ISSUE TITLE
flutter 3.0.0 is detecting issue with the library

### ISSUE THREAD

**Issue by Bahrom2101** [diegoveloper/flutter_percent_indicator#157]
/D:/flutter_windows_3.0.0-stable/flutter/.pub-cache/hosted/pub.dartlang.org/percent_indicator-4.0.0/lib/linear_percent_indicator.dart(162,20): warning G1E0FE241: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null. [D:\FlutterProjects\billz_cashier_desktop\build\windows\flutter\flutter_assemble.vcxproj]

**Comment by RakulAgn** [comment]
whats the solution ?

**Comment by diegoveloper** [comment]
new version is ready

**Comment by RakulAgn** [comment]
Thanks Dude

**Comment by YouSour** [comment]
awesome , thank you
