### ISSUE TITLE
Build failed on Flutter 2.10.

### ISSUE THREAD

**Issue by masahiro-ikemoto** [diegoveloper/flutter_percent_indicator#160]
The version 4.2.0 was faild to build on Flutter 2.10 (or earlier).
```
ERROR: .pub-cache/hosted/pub.dartlang.org/percent_indicator-4.2.0/lib/linear_percent_indicator.dart:162:29: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
ERROR:  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../development/flutter/packages/flutter/lib/src/widgets/binding.dart').
ERROR: Try calling using ?. instead.
ERROR:     WidgetsBinding.instance.addPostFrameCallback((_) {
```

I think to fix it with which one of below:
- Rollback changes and release once, and release with setting flutter version lower limit (`flutter: '>=2.12.0'`) in pubspec.yaml ,again.

- Keep null-aware operator and ignore warnings for analyzing.
```
// ignore:invalid_null_aware_operator
WidgetsBinding.instance?.addPostFrameCallback((_)
```

- Use _ambigurate method like other packages.
```
T? _ambiguate<T>(T? value) => value;
_ambiguate(WidgetsBinding.instance)?.addPostFrameCallback((_)
```

**Comment by diegoveloper** [comment]
Use the previous version of this package

**Comment by masahiro-ikemoto** [comment]
>Use the previous version of this package

Even if that, I think you sould set lowe limit of fluttter version to let to lock previous version on 2.10.

**Comment by diegoveloper** [comment]
That's a good idea. Would you mind to send a PR?

Thank you
