### ISSUE TITLE
Warning: The class 'WidgetsBinding' cannot be null.

### ISSUE THREAD

**Issue by HugoPowerMex** [diegoveloper/flutter_percent_indicator#163]
Warning: The class 'WidgetsBinding' cannot be null.

**Comment by HugoPowerMex** [comment]
hola diego saludos me da ese detalle con version de flutter 2.10.4, saludos  diegoveloperYT!!

**Comment by diegoveloper** [comment]
Hola, puedes usar la versión `4.0.1`, de lo contrario te saldrá ese warning de Flutter 3.0.

**Comment by HugoPowerMex** [comment]
Listo ya quedo gracias diego
