### ISSUE TITLE
app is not running, because of WidgetsBinding?.instance.addPostFrameCallback((_)

### ISSUE THREAD

**Issue by guvanch-amangeldiyev-idf** [diegoveloper/flutter_percent_indicator#164]
Launching lib/main.dart on iPhone 13 in debug mode...
lib/main.dart:1
Xcode build done.                                           13,1s
Failed to build iOS app
Error output from Xcode build:
↳
    objc[9671]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1e5f16b90) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103e882c8). One of the two will be used. Which one is undefined.
    objc[9671]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1e5f16be0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103e88318). One of the two will be used. Which one is undefined.
    ** BUILD FAILED **
Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/_q/9swcthyx13l07kyknkj99xc40000gn/T/flutter_tools.68NsIg/flutter_ios_build_temp_dir2Wtmw2/temporary_xcresult_bundle
: Warning: The class 'WidgetsBinding' cannot be null.
../…/lib/linear_percent_indicator.dart:162
    Try replacing '?.' with '.'
        WidgetsBinding?.instance.addPostFrameCallback((_) {
        ^^^^^^^^^^^^^^
: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
../…/lib/linear_percent_indicator.dart:162
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Documents/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    Try calling using ?. instead.
        WidgetsBinding?.instance.addPostFrameCallback((_) {
                                 ^^^^^^^^^^^^^^^^^^^^
    Failed to package /Users/guvanch/flutter_projects/test_appbar_animation.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the Runner editor. (in target 'Runner' from project 'Runner')
    Result bundle written to path:
    	/var/folders/_q/9swcthyx13l07kyknkj99xc40000gn/T/flutter_tools.68NsIg/flutter_ios_build_temp_dir2Wtmw2/temporary_xcresult_bundle
Could not build the application for the simulator.
Error launching application on iPhone 13.
Exited (sigterm)

lines
../…/lib/linear_percent_indicator.dart:162
../…/lib/linear_percent_indicator.dart:162

[✓] Flutter (Channel stable, 2.10.1, on macOS 12.1 21C52 darwin-arm)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.1)
[✓] VS Code (version 1.64.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by keitokusano** [comment]
Facing the same problem.

**Comment by diegoveloper** [comment]
Please see the closed issues.

**Comment by zky6628** [comment]
I solved the problem with version 4.0.1：
4.0.1 code :

`WidgetsBinding.instance?.addPostFrameCallback((_) {
      if (mounted) {
        setState(() {
          _containerWidth = _containerKey.currentContext?.size?.width ?? 0.0;
          _containerHeight = _containerKey.currentContext?.size?.height ?? 0.0;
          if (_keyIndicator.currentContext != null) {
            _indicatorWidth = _keyIndicator.currentContext?.size?.width ?? 0.0;
            _indicatorHeight =
                _keyIndicator.currentContext?.size?.height ?? 0.0;
          }
        });
      }
    });`
