### ISSUE TITLE
add a border to the progressIndicator

### ISSUE THREAD

**Issue by lcyper** [diegoveloper/flutter_percent_indicator#166]
- border width
- boder color

so this way can we have a transparent background and steel seen the circularProgresIndicator.

thanks

**Comment by diegoveloper** [comment]
sorry for the late response, did you fix this issue?

**Comment by lcyper** [comment]
i used this properties: that work for me.

`CircularPercentIndicator(
                lineWidth: 10,
                circularStrokeCap: CircularStrokeCap.round,
                progressColor: Theme.of(context).colorScheme.secondary,)
`
