### ISSUE TITLE
v4.2.1 ios Compilation failed

### ISSUE THREAD

**Issue by tangbincheng** [diegoveloper/flutter_percent_indicator#168]
../../FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/percent_indicator-4.2.1/lib/linear_percent_indicator.dart:162:5: Warning: The class 'WidgetsBinding' cannot be null.
    Try replacing '?.' with '.'
        WidgetsBinding?.instance.addPostFrameCallback((_) {
        ^^^^^^^^^^^^^^
    ../../FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/percent_indicator-4.2.1/lib/linear_percent_indicator.dart:162:30: Error: Method 'addPostFrameCallback' cannot be called on
    'WidgetsBinding?' because it is potentially null.
     - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../FlutterSDK/flutter/packages/flutter/lib/src/widgets/binding.dart').
    Try calling using ?. instead.
        WidgetsBinding?.instance.addPostFrameCallback((_) {
                                 ^^^^^^^^^^^^^^^^^^^^
    Failed to package /Users/peripage/Documents/ALD_SVN/Flutter.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    note: Removed stale file

**Comment by diegoveloper** [comment]
https://github.com/diegoveloper/flutter_percent_indicator/issues?q=is%3Aissue+is%3Aclosed
