### ISSUE TITLE
Incorrect place of ? in postFramCallBack

### ISSUE THREAD

**Issue by wajahatiqbal22** [diegoveloper/flutter_percent_indicator#169]
The position of the question mark init state is incorrect,

PREV:
WidgetsBinding?.instance.addPostFrameCallback

FIX:
WidgetsBinding.instance?.addPostFrameCallback

Kindly change that in LinearPercentIndicator class

**Comment by diegoveloper** [comment]
https://github.com/diegoveloper/flutter_percent_indicator/issues?q=is%3Aissue+is%3Aclosed
