### ISSUE TITLE
Position of the widget indicator above the indicator

### ISSUE THREAD

**Issue by LeeBumSeok** [diegoveloper/flutter_percent_indicator#170]
Is there a way to display the widgetindicator above the indicator?

This is example.
<img width="482" alt="image" src="https://user-images.githubusercontent.com/28581806/175863812-32a2aaa4-c965-4b92-b07a-bb169d14442d.png">

**Comment by diegoveloper** [comment]
I think you can just create a `Column` widget and add the content above your `LinearPercentIndicator`.
