### ISSUE TITLE
Version 4.2.2 not Compatible with Flutter version 2.10.3 (Dart version	2.16.1)

### ISSUE THREAD

**Issue by Rui-Trindade406** [diegoveloper/flutter_percent_indicator#183]
Hello I have the 2.10.3 flutter version in my code.
![Screenshot 2022-10-31 at 12 04 27](https://user-images.githubusercontent.com/86790078/199003915-a398349a-386e-4e79-90d9-acab1498db64.png)

 And when I try to upgrade my version to use the 4.2.2 I receive that the Flutter version is insufficient to upgrade your package. displays the following message
 
![Screenshot 2022-10-31 at 12 01 06](https://user-images.githubusercontent.com/86790078/199004455-fd5d3fe1-8c75-479f-b3d0-f7c423e48a9f.png)

According to the package page you support Dart sdk 2.12.0. Which according to Flutter documentation my version is 2.16.1 as shown below. 

![Screenshot 2022-10-31 at 12 09 17](https://user-images.githubusercontent.com/86790078/199004630-6d18ebf4-1dff-4da7-ae59-8f13fb84d50f.png)

![Screenshot 2022-10-31 at 12 11 05](https://user-images.githubusercontent.com/86790078/199004968-42137e09-b4dc-475e-a566-065ec68c1188.png)
![Screenshot 2022-10-31 at 12 11 18](https://user-images.githubusercontent.com/86790078/199004991-7bc95907-c9b0-4326-a6f2-649a7da58a4a.png)

Please help me understand this issue
Thank you for your attention

**Comment by diegoveloper** [comment]
Use this version `2.1.9+1` or upgrade your flutter version

**Comment by Rui-Trindade406** [comment]
I can use the version 4.2.1 but the 4.2.2 does that error. your package from one version to the next raises the sdk version but does not advertise in the package info. And you should correct the information if it is not correct. 
the Dart version is not the flutter version the dart version 2.12 is before referring to 2.0.0 Flutter version.

![Screenshot 2022-10-31 at 15 28 00](https://user-images.githubusercontent.com/86790078/199045842-74746781-6a9b-4233-b959-cbaf2c0e0bc6.png)

**Comment by diegoveloper** [comment]
my recommendation is to update your flutter version, 2.10 is too low, the current stable version is `3.3.6`

**Comment by diegoveloper** [comment]
We don't add dart version on the README of the package, you can check the min version on the releases , https://pub.dev/packages/percent_indicator/versions you can see.

4.2.2 supports Dart 2.12 but it's using Flutter 3.x+ (We restricted the flutter sdk version on that version).

You should update to Flutter 3.x otherwise you will find more errors on other packages or you will use packages with a lot of bugs (fixed on newer versions).

**Comment by Rui-Trindade406** [comment]
then I suggest you change the min Dart version number since it is misleading

**Comment by diegoveloper** [comment]
you can check the restrictions here, this is open source, everyone can check this -> https://github.com/diegoveloper/flutter_percent_indicator/blob/master/pubspec.yaml#L12

**Comment by Rui-Trindade406** [comment]
do you know there is no flutter version 2.12. 

![Screenshot 2022-10-31 at 16 11 46](https://user-images.githubusercontent.com/86790078/199056047-72434235-d45b-4d76-b82f-d01696504ca0.png)

this is my limitation of my app. For sdk you allow older than the null safety is introduced, but then you limit the flutter version...

**Comment by diegoveloper** [comment]
Another solution is fork the project and change as you want
