### ISSUE TITLE
Using fillColor creates a rectangular fill not circular

### ISSUE THREAD

**Issue by aneeskA** [diegoveloper/flutter_percent_indicator#189]
Sample code

```
CircularPercentIndicator(
        radius: 25.0,
        lineWidth: 3,
        center: Icon(
          Icons
              .workspace_premium_outlined,
          color: Colors.white,
        ),
        progressColor: Colors.white,
        backgroundColor:
            Colors.deepPurple.shade400,
        fillColor: Colors.green,
        percent: 1.0,
      ),
```

Screenshot
<img width="175" alt="image" src="https://user-images.githubusercontent.com/514419/210181898-e1b8cb97-5517-4035-baa5-189403f00cc8.png">

The last green filled corresponds to the above code.
Same as https://github.com/diegoveloper/flutter_percent_indicator/issues/125

**Comment by aneeskA** [comment]
@diegoveloper Please take a look at this if you can.

**Comment by diegoveloper** [comment]
Can you add a ClipOval above CircularPercentIndicator?

**Comment by aneeskA** [comment]
Wow! I didn't know such a widget existed! It fixes the problem :) 

```
ClipOval(
    child: CircularPercentIndicator(
      radius: 25.0,
      lineWidth: 3,
      center: Icon(
        Icons
            .workspace_premium_outlined,
        color: Colors.white,
      ),
      progressColor: Colors.white,
      backgroundColor: Colors
          .deepPurple.shade400,
      fillColor: Colors.green,
      percent: 1.0,
    ),
  ),
```

result

<img width="183" alt="image" src="https://user-images.githubusercontent.com/514419/210182641-675dbaf3-6339-462e-8d9f-8e6c0c9d6b1a.png">

**Comment by aneeskA** [comment]
@diegoveloper May be add an example to the README for this specific case?

**Comment by diegoveloper** [comment]
Great

**Comment by diegoveloper** [comment]
Would you mind to send a PR?

**Comment by aneeskA** [comment]
> Would you mind to send a PR?
> […](#)

Yes, will do that. ✌️

**Comment by Ngochiendev** [comment]
great, Thank you for providing the solution
