### ISSUE TITLE
Change text color based on linear progress bar color.

### ISSUE THREAD

**Issue by theArtechnology** [diegoveloper/flutter_percent_indicator#19]
When the prorgress bar is filled, the Text color try to adapt to the background color.

For ex. The progress is light green, the text can't be white, it should be sort of black for e.g.

It is just a suggestion !

**Comment by theArtechnology** [comment]
It's the best example I can get: https://codepen.io/robinrendle/pen/wKqmbW

**Comment by diegoveloper** [comment]
The issue is that can use any Widget inside the Linear Progress Bar (not only text), but feel free to improve and send a PR.
