### ISSUE TITLE
Different version shows different size of circle for same radius in CircularPercentIndicator

### ISSUE THREAD

**Issue by MdNaimHasan** [diegoveloper/flutter_percent_indicator#191]
Version 3.4.0 and 4.2.1 shows different size of circle for same radius.
In version 4.2.2, when radius is increased, eventually it goes outside of the ancestor container.

**Comment by diegoveloper** [comment]
https://pub.dev/packages/percent_indicator/changelog#400

**Comment by MdNaimHasan** [comment]
> https://pub.dev/packages/percent_indicator/changelog#400
In version 4.2.2, when radius is increased, it doesn't show overflow error. Instead it draws circle outside of its ancestor container.
![2](https://user-images.githubusercontent.com/120188331/214106232-443195f5-d01e-4220-84f2-bd0f2cc0a4f7.png)

**Comment by diegoveloper** [comment]
you can try stackoverflow for those kind of questions

**Comment by MdNaimHasan** [comment]
> you can try stackoverflow for those kind of questions

When tried with version  4.2.1, it gave overflow error which is acceptable. But version 4.2.2 doesn't give any overflow error. Also if you see closely, the circles went outside of their box and at some place they went over the tile and somewhere they went behind but over the background.
