### ISSUE TITLE
Update Progress on setState with Animation

### ISSUE THREAD

**Issue by JotaFerreira** [diegoveloper/flutter_percent_indicator#2]
Progress not update on setState when animation = true

double percent = 0.1;

// not works
LinearPercentIndicator(
        animation: true,
        animationDuration: 1000,
        percent: percent
)

setState(() {
          percent = 0.2;
        });

// works
LinearPercentIndicator(
        animation: false, // here
        animationDuration: 1000,
        percent: percent
)

setState(() {
          percent = 0.2;
 });

**Comment by diegoveloper** [comment]
Hello, you don't need to use setState if you use animation: true, it will animate automatically

**Comment by JotaFerreira** [comment]
@diegoveloper ok! thanks, nice package!

**Comment by erperejildo** [comment]
@diegoveloper it doesn't work for me if I remove the `SetState`:

```
void _startTimer() {
    var sub = countDownTimer.listen(null);
    sub.onData((duration) {
      // setState(() {
      _current = _start + duration.elapsed.inSeconds;
      //  });
    });

    sub.onDone(() {
      print("Done");
      sub.cancel();
    });
  }
```

and:
```
Widget build(BuildContext context) {
final double percentage = _current * 100 / 10;
...
animation: true,
percent: percentage * 0.01,
```
