### ISSUE TITLE
Fill the linear indicator vertically

### ISSUE THREAD

**Issue by rawestmoreland** [diegoveloper/flutter_percent_indicator#21]
I'd love to be able fill the linear percentage indicators from bottom to top. Maybe I'm missing how this can be accomplished?

**Comment by diegoveloper** [comment]
Try wrapping the LinearPercentIndicator widget inside RotatedBox, like this : 
`RotatedBox(
          quarterTurns: 1,
          child: LinearPercentIndicator(
          ...
 ) )
`
Play with the `quarterTurns` value

**Comment by rawestmoreland** [comment]
Perfect! Thank you.
