### ISSUE TITLE
Linear Gradient

### ISSUE THREAD

**Issue by nikhiljha** [diegoveloper/flutter_percent_indicator#22]
Hi! Thank you for the package!

I was wondering if there was a way to make the color a gradient? The solid color looks a bit off in comparison to the rest of my app.

Something like this... (iOS Clock App)

![photo_2019-04-02_18-14-04](https://user-images.githubusercontent.com/2773700/55446108-2ad96100-5573-11e9-87dc-0adac9259004.jpg)

**Comment by diegoveloper** [comment]
Let me check about that

**Comment by diegoveloper** [comment]
Hi @nikhiljha you can try using the git repo directly, like this:


Edit your pubspec.yaml file

```
percent_indicator:
    git: https://github.com/diegoveloper/flutter_percent_indicator/

```

Use the gradient

```
          CircularPercentIndicator(
            radius: 100.0,
            lineWidth: 10.0,
            percent: 0.5,
            center: Text("50%"),
            circularStrokeCap: CircularStrokeCap.round,
            backgroundColor: Colors.grey,
            linearGradient: LinearGradient(
              begin: Alignment.topCenter,
              end: Alignment.bottomCenter,
              colors: [Colors.orange, Colors.yellow],
            ),
          ),
```

Let me know if it works for you.

**Comment by cstn-l** [comment]
It worked well for my `LinearPercentageIndicator`, i would love to have it in the next update!

**Comment by nikhiljha** [comment]
Somehow missed the first notification. It looks great! Thank you!

**Comment by diegoveloper** [comment]
It's already published : https://pub.dev/packages/percent_indicator/versions/2.0.0   
Thanks for the feedback.
