### ISSUE TITLE
Feature request: Please consider adding non-constant width

### ISSUE THREAD

**Issue by neiljaywarner** [diegoveloper/flutter_percent_indicator#23]
Just a feature request; please consider since width is assigned directly to width in a container, it appears to be required as a double .
e.g. if you leave it off you get a circle if you have 1.0 percent value.

I don't actually know how to get max width of the screen, but even if i did that doesn't seem likethe right way. 

Progress indicators that fill the entire screen minus padding (rather than a hardcoded width) seem like a common use case?

**Comment by diegoveloper** [comment]
Did you try using  MediaQuery.of(context.)size.width ?

**Comment by neiljaywarner** [comment]
that does mostly work, my apologies. it doesn't work quite as easy as the default LinearProgressIndicator (so far), but i think it will be ok.  thanks for the tip...
