### ISSUE TITLE
Feature request: possibility to manage over 100% with the possibility to change bar color

### ISSUE THREAD

**Issue by enricobenedos** [diegoveloper/flutter_percent_indicator#26]
Good morning,
thank you for the nice package!
It will be very beautiful to have the possibility to manage the over 100% percentage. Now if I have a 'percent' value > 1.0 the widget return an exception. My idea is to show the over 100 percentage for example:
--> 1.5 - 150%
It can be very useful in some case. 
Then if this feature will be implemented it will be perfect to have a dedicated bar color when the percentage is over 100%.

**Comment by diegoveloper** [comment]
I think it could be handled by the logic of the app that is using this package.

**Comment by DennisAshford** [comment]
Does this work? I am getting an error when the percentage is > 100% with the package.

**Comment by negrovirasoro** [comment]
> Does this work? I am getting an error when the percentage is > 100% with the package.

any solution?
I am getting a crash if I go over 100

**Comment by diegoveloper** [comment]
100 = 1.0 is the maximum value, before send the value you can use clamp.

Yourvalue.clamp(0,1)

**Comment by negrovirasoro** [comment]
percent: (value.balance / value.budget).clamp(0, 1),

#Gracias
