### ISSUE TITLE
Feature Request: Dynamic Progress Color

### ISSUE THREAD

**Issue by mliitfall** [diegoveloper/flutter_percent_indicator#30]
Hi, love this package. Thank you!
Only two thing to be added and I think it was important.
First is adding a dynamic color change based on percentage. Lets says Linear Percent Indicator, from the most left side is Colors.red and to the most right is Colors.green. It's like a health bar.
Second thing is I want to know how to remove padding of Linear Percent Indicator padding?
Something like this :
[Image](https://imgur.com/a/xprpVPR)
It really take some space on the phone. The top and bottom padding how can i remove it?

**Comment by diegoveloper** [comment]
Hi, yes, that could be a nice feature, I'll keep this issue open , maybe some people of the community could work on this feature.

About the issue you have with the padding (bottom/top), could you add the code you are using? maybe create a simple sample to recreate the issue.

**Comment by mliitfall** [comment]
> About the issue you have with the padding (bottom/top), could you add the code you are using? maybe create a simple sample to recreate the issue.

Thanks for the quick reply,
It's just a simple code from the explanation :
```
Scaffold(
        appBar: AppBar(
          title: Text(widget.itemName),
        ),
        body: Container(
          child: LinearPercentIndicator(
            width: 170.0,
            animation: true,
            animationDuration: 1000,
            lineHeight: 20.0,
            leading: new Text("left content"),
            trailing: new Text("right content"),
            percent: 0.2,
            center: Text("20.0%"),
            linearStrokeCap: LinearStrokeCap.butt,
            progressColor: Colors.red,
          ),
        )
```
The bar padding on each side is look like this [Image](https://imgur.com/a/xprpVPR).
How to simple disable the padding? Because it take some space.

**Comment by diegoveloper** [comment]
Vertical padding removed in new version `2.1.0`
