### ISSUE TITLE
Suggestion: Linear indicator should display only part of linear gradient

### ISSUE THREAD

**Issue by shaxxx** [diegoveloper/flutter_percent_indicator#31]
I believe current implementation of linear gradient does not fit well with linear percent indicator use case. IMHO indicator should shade only part of linear gradient (according to progress value), not entire gradient. 
For example bellow I specified linear gradient with 4 colors (red, orange, yellow, green) to create 'VU effect'.  Upper progress bar is the way I believe indicator should render gradient, lower one is current behavior. No matter what progress value is set entire gradient is visible.

![gradient](https://user-images.githubusercontent.com/1778875/59978371-eb536b80-95db-11e9-9cd3-5cd814ad99ad.png)

It's just a matter of changing shader offset values in 2 places (original code below)
https://github.com/diegoveloper/flutter_percent_indicator/blob/afbef0e558d8b6cbfecb45e6d9df7b58d6bbdfda/lib/linear_percent_indicator.dart#L271-L272

https://github.com/diegoveloper/flutter_percent_indicator/blob/afbef0e558d8b6cbfecb45e6d9df7b58d6bbdfda/lib/linear_percent_indicator.dart#L279-L280

I can make a PR but I feel this needs some feedback from you.
Can this functionality at least be available as an option?
Thanks for the great widget!

**Comment by diegoveloper** [comment]
I understand, you can send a PR making it customizable ;)

**Comment by shaxxx** [comment]
Should both circular and linear indicators have same option?

**Comment by diegoveloper** [comment]
I think it should be available only for Linear, now we have a bug on the
gradient for Circular.

**Comment by diegoveloper** [comment]
done! and published :)

**Comment by MobileMon** [comment]
Yeah I really need this functionality for the Circular. Any clue how to implement?

**Comment by shaxxx** [comment]
I had to make kinda 'hackish' solution for myself.
You can see it in action [HERE](https://labs-public-dl.xda-cdn.com/screenshots/aa986a95-6749-4ce4-b208-52b872337f0d.jpg) or in [VIDEO](https://www.youtube.com/watch?v=z5L0eD7KB08).
Source code [HERE](https://github.com/shaxxx/Signalmeter2/blob/master/lib/src/ui/common/circular_progress_view.dart)

Also since then, some new packages became available.
Check out [THIS ](https://pub.dev/packages/sleek_circular_slider)one.
You can see it in action [HERE](https://www.youtube.com/watch?v=ECXdRYs89QY&feature=youtu.be)
I've never tried it though.
