### ISSUE TITLE
Radius parameter is actually a diameter 

### ISSUE THREAD

**Issue by shorben07** [diegoveloper/flutter_percent_indicator#33]
CircularPercentIndicator has a property `final double radius;` but in implementation, it is used as a diameter:
```
Container(
        height: widget.radius + widget.lineWidth,
        width: widget.radius,
```
Here we get the real radius by dividing by two
```
CirclePainter(
              radius: (widget.radius / 2) - widget.lineWidth / 2,
```
Please read more info at link https://www.mathlearnit.com/circle-circumference.html
![circle-circumference-radius-diameter](https://user-images.githubusercontent.com/36268266/61691491-5c4d8680-ad34-11e9-9e90-e1160c31e875.png)

**Comment by diegoveloper** [comment]
You are right, I think we need to update the name of the field and the doc, the issue is it will be a breaking change

**Comment by shorben07** [comment]
@diegoveloper It is not really a big issue. For me, it took a couple of minutes to figure out why the circle is smaller than it should be.
Thanks for the great library!

**Comment by nguyenxndaidev** [comment]
> the issue is it will be a breaking change

You could introduce new field `diameter` and deprecated the field `radius`, then in DartDoc asking people to migrate to `diameter` and warn them radius will be removed in the next major release.

**Comment by diegoveloper** [comment]
PRs are open :)

**Comment by slimlime** [comment]
> > the issue is it will be a breaking change
> 
> You could introduce new field `diameter` and deprecated the field `radius`, then in DartDoc asking people to migrate to `diameter` and warn them radius will be removed in the next major release.

^

I ended up hard breaking change updating a fork (gotta go fast!) along with a slew of other refactors

Might make time far in the future for a more maintainable release schedule (and also backport re-up nullsafety)

Radius vs diameter dissonance was a fun discovery when mock testing UI with boxes

**Comment by diegoveloper** [comment]
@slimlime if you want to send a PR, you are welcome.

**Comment by nvshah** [comment]
@diegoveloper 
Attempted a simple attempt for aforementioned issue (with minimal changes) accounting diameter instead of radius whilst building the Widget

PR ref :- https://github.com/diegoveloper/flutter_percent_indicator/pull/140
