### ISSUE TITLE
Customize Stroke Cap

### ISSUE THREAD

**Issue by LenvZyl** [diegoveloper/flutter_percent_indicator#37]
Is there any possibility to create a custom stroke Cap like so 
<img width="136" alt="Screenshot 2019-09-13 at 11 40 40" src="https://user-images.githubusercontent.com/20842612/65022252-e9761b80-d930-11e9-9e11-1fd745cf6930.png">

**Comment by diegoveloper** [comment]
https://github.com/diegoveloper/flutter_percent_indicator/blob/master/lib/circular_percent_indicator.dart#L49

**Comment by LenvZyl** [comment]
How do I highlight the StrokeCap to be a different colour?
