### ISSUE TITLE
There is padding when i set header and footer  is null

### ISSUE THREAD

**Issue by q869939686** [diegoveloper/flutter_percent_indicator#42]
![image](https://user-images.githubusercontent.com/29123332/68271895-0a3f2f80-009d-11ea-96b7-c4935882c269.png)
![image](https://user-images.githubusercontent.com/29123332/68272015-643ff500-009d-11ea-8265-b028618ad108.png)

**Comment by diegoveloper** [comment]
Add a small simple code to run on my own and reproduce the issue. Thanks
