### ISSUE TITLE
Error when leaving a page with unfinished animation

### ISSUE THREAD

**Issue by joknjokn** [diegoveloper/flutter_percent_indicator#43]
Hi - Thanks for the plugin.

I use the CircularPercentIndicator with animation. If I leave the page with the indicator before the animation finished, I get this error:

```
[log] setState() called after dispose(): _OtherProfileState#f22c8(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
```

Is it something that should be fixed in the plugin, or something I should handle somehow?

Thanks.

**Comment by diegoveloper** [comment]
Could you add a simple file code to reproduce the issue here. Thanks

**Comment by joknjokn** [comment]
It's basically just a stateful widget with this in the build():

```
CircularPercentIndicator(
                    radius: 160.0,
                    lineWidth: 10.0,
                    startAngle: 90,
                    percent: (1.00 - userLevelData[2]) ?? 0.0,
                    center: new Text(""),
                    //backgroundColor: gamify.pointsToColor(otherUser.points),
                    backgroundColor: globals.colorList[1],
                    progressColor: globals.colorList[2],
                    animation: true,
                    animationDuration: 2000,
                    circularStrokeCap: CircularStrokeCap.butt,
                  )
```

So, if I leave the page before 2000 milliseconds, the error occours. I guess it's because the plugin doesn't check for if(mounted) when setting states for the animation?

**Comment by diegoveloper** [comment]
Yeah, probably , could you try fixing the code and sending a PR to the
package? :)

**Comment by joknjokn** [comment]
I've never tried that before. Not sure you want me to try? :P

(Don't know how to do it.)

**Comment by diegoveloper** [comment]
Hmm ok, I will try to fix the issue. But please add here a simple file
 main.dart , with minimum code to reproduce the issue.

**Comment by joknjokn** [comment]
I downloaded and imported the plugin manually, which removed the error - and know I can't reproduce the error with the auto-imported version (percent_indicator: ^2.1.1+1).

No clue why. I'll close this and report back if it happens again. Thanks for the quick reply.
