### ISSUE TITLE
Flutter web doesn't support this package.

### ISSUE THREAD

**Issue by Parmendrakumar** [diegoveloper/flutter_percent_indicator#44]
On mobile its working fine, but on web its not working.

Getting build error:
Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

**Comment by diegoveloper** [comment]
hello,  did you get it to work ?

**Comment by grathi** [comment]
Web also working fine. However, there is another issue in web the charts being blurred
