### ISSUE TITLE
Progress Color not working.

### ISSUE THREAD

**Issue by basha97** [diegoveloper/flutter_percent_indicator#48]
Sometime the progressColor in app does not work , i don't know why it happening suddenly. It was working well before and this problem occurs
![photo_2020-03-17_11-55-54](https://user-images.githubusercontent.com/44155715/76828150-4dc55980-6846-11ea-8a8e-a2f1ac4bc410.jpg)
![carbon](https://user-images.githubusercontent.com/44155715/76828163-5453d100-6846-11ea-9367-2112c924e320.png)

**Comment by diegoveloper** [comment]
Add a simple code to reproduce the issue.

**Comment by basha97** [comment]
Working fine
