### ISSUE TITLE
Gradient Color

### ISSUE THREAD

**Issue by JCarlos3296** [diegoveloper/flutter_percent_indicator#49]
Good morning Daniel,
Can't progressColor be made with a gradient color?
For example, if I have 30% I have a red color with opacity and at the end when I reach 100% I have the other fraction completely red.

Thanks for reading the comment.

**Comment by McSam94** [comment]
Any update on this?

**Comment by diegoveloper** [comment]
Add a better explanation about what you need.  An image would be fine.

**Comment by shahidcodes** [comment]
I think what he wants is setting gradient for progress color. I can see some options for linear progress bar. But is there a way to make it like the below picture in case of circular progress?

![IMG_20200420_174952](https://user-images.githubusercontent.com/17620737/79750966-718d2b00-832f-11ea-801e-a3b7177dc8eb.jpg)

**Comment by diegoveloper** [comment]
Yes, the circular percent indicator already has a linearGradient property that you can use:  https://github.com/diegoveloper/flutter_percent_indicator/blob/master/lib/circular_percent_indicator.dart#L46
