### ISSUE TITLE
CircularPercentIndicator add endAngle parameter

### ISSUE THREAD

**Issue by boskokg** [diegoveloper/flutter_percent_indicator#53]
We need endAngle for the case like:

![Screenshot 2020-04-14 at 09 18 18](https://user-images.githubusercontent.com/18428281/79196956-9268f400-7df6-11ea-9627-172cdb4c4e35.png)

**Comment by diegoveloper** [comment]
Check this sample
https://github.com/diegoveloper/flutter_percent_indicator/blob/3555894792dd0e250d592de4aa4a9c1a66be516f/example/lib/sample_circular_page.dart#L47

You could get the same result

**Comment by boskokg** [comment]
Thanks!!!
