### ISSUE TITLE
how to do the background of the circle

### ISSUE THREAD

**Issue by superciccio** [diegoveloper/flutter_percent_indicator#56]
Hi,

your library is very good, I do have a question.

now I'm doing this (see image)

`
CircularPercentIndicator(
            radius: 200.0,
            lineWidth: 10.0,
            percent: _percent,
            animation: true,
            fillColor: UIConstant.backgroundColor,
            animateFromLastPercent: true,
            center: SizedBox(
              child: Stack(
                children: <Widget>[
                  
                ],
              ),
              height: 180,
              width: 200,
            ),
            backgroundColor: UIConstant.darkColor,
            progressColor: UIConstant.lightColor,
          ),
`

I only want fillcolor to be the background of the circle.

how can I achieve that ?

also `Container` is creating a square instead of clipping 
should we use `ClipRRect` to the `container`

![Screenshot_1589713193](https://user-images.githubusercontent.com/4390182/82142793-db1d2e00-9836-11ea-987c-606ff1f3201d.png)

Thanks

**Comment by diegoveloper** [comment]
Yes, you can use cliprrect or clipoval

**Comment by superciccio** [comment]
thanks for the reply. 
still something doesn't look quite right 

![Screenshot_1589730046](https://user-images.githubusercontent.com/4390182/82153119-745f3b00-985d-11ea-9e35-51e56118c0cf.png)

 look at the end of the circle
I've tried different clipbehaviour none of them fix this.

any idea ? :)

**Comment by diegoveloper** [comment]
Add a Container with color
Add circularpercentindicator
Wrap all inside ClipOval but add a different radius , more that you have in
the circle

**Comment by superciccio** [comment]
that didn't work, but is a better now !
the line that draws the percentage is a bit rocky tho :/

**Comment by diegoveloper** [comment]
What is the code and the result

**Comment by superciccio** [comment]
https://gist.github.com/superciccio/3e32377bd6cfbcbc4520caafd0137797

![Screenshot_1589731239](https://user-images.githubusercontent.com/4390182/82153539-f2bcdc80-985f-11ea-934e-9417d02add26.png)

I also change the height of the container `height: widget.radius + widget.lineWidth,`
cause before there was a a little space between the inner and outer circle

**Comment by diegoveloper** [comment]
You need something like this :


ClipOval
   Padding
     Container  //no decoration, use ->  color: UIConstant.darkColor,
       CicularPercentIndicator

*    Diego Velásquez*
*www.diegoveloper.com <http://www.diegoveloper.com>*

**Comment by superciccio** [comment]
![Screenshot_1589731239](https://user-images.githubusercontent.com/4390182/82153903-429ca300-9862-11ea-9234-0080156491b3.png)
 then I come back to ground 0
the square around the circle, which i don't want

**Comment by superciccio** [comment]
and also the line is still rocky at the edge

**Comment by diegoveloper** [comment]
code please

**Comment by superciccio** [comment]
I've updated the gist 

https://gist.github.com/superciccio/3e32377bd6cfbcbc4520caafd0137797

with the colour that I'm using

basically I want the circle background blue, the line of the progress `Color.fromRGBO(162, 201, 238, 1.0)`

**Comment by diegoveloper** [comment]
I guess I was wrong, use ClipOval > Container > Padding>  CircularPercent
>
Use a bigger padding like 2 o 3

**Comment by superciccio** [comment]
nope, it doesn't make any difference.
also if you use clipoval you don't have a full circle (the edges left and right are very rough)

**Comment by superciccio** [comment]
and I still have the square around the circle (which I don't want)

**Comment by diegoveloper** [comment]
Check this sample I created :
https://dartpad.dev/a76e2483e9c40bc98388df0de6a589d5

**Comment by superciccio** [comment]
the dartpad works, as expected
but your plugin creates the square in my code which I don't get why...
like I said to not have it. I've to do this

`decoration: BoxDecoration(
            color: UIConstant.darkColor,
                borderRadius: BorderRadius.circular(100)),
            clipBehavior: Clip.antiAliasWithSaveLayer,`

thanks anyway I'll keep it like this (no square and clipping)

**Comment by crushman1** [comment]
Hi, just to add to the various work-arounds. What i was able to do was wrap the percentage text in a Container and make the container shape circle. you get the desired effect that was expected from `fillColor`
```
new CircularPercentIndicator(
                          reverse: true,
                          arcType: ArcType.FULL,
                          backgroundColor: Colors.white30,
                          animationDuration: 2000,
                          animation: true,
                          circularStrokeCap: CircularStrokeCap.round,
                          radius: 60.0,
                          lineWidth: 5.0,
                          percent: 0.5,
                          center: Container(
                            decoration: BoxDecoration(
                              shape: BoxShape.circle,
                              color: Colors.white30
                            ),
                              child: Center(child: new Text("50%", style: TextStyle(fontWeight: FontWeight.bold),))),
                          progressColor: Colors.black,
                        )
```

**Comment by Oliver530** [comment]
Unfortunately, no workaround worked properly for me. In the end, I decided to work with a stack:

```
CircularPercentIndicator(
      radius: 50,
      lineWidth: 6,
      animation: true,
      percent: 0.5,
      backgroundColor: Colors.white,
      circularStrokeCap: CircularStrokeCap.round,
      progressColor: rating.color,
      center: Stack(
        alignment: AlignmentDirectional.center,
        children: [
          Container(
            width: 40,
            height: 40,
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              color: Colors.white,
            ),
          ),
          Text(
            rating.value.toString(),
            style: TextStyle(
              color: rating.color,
              fontWeight: FontWeight.bold,
              fontSize: 20.0,
            ),
          )
        ],
      ),
    )
```
