### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by mester9000** [diegoveloper/flutter_percent_indicator#67]
Is it possible to do the following thing?
I navigate to a new screen and I use a linear percent indicator there. I would like it to be for example at 60% without animation for the first time. After a certain amount of time this indicator goes to 80%, but this time with animation, from 60% to 80%.
I tried to set the animation property to false, and after a little time to true but it did not work.

**Comment by diegoveloper** [comment]
Did you try animateFromLastPercent?

**Comment by mester9000** [comment]
Yes I did, but it didn't work. It seems like if I set  the animation to false, and then set it to true, it won't animate.

**Comment by diegoveloper** [comment]
well , PRs are welcome in case you want to add extra features
