### ISSUE TITLE
On Complete

### ISSUE THREAD

**Issue by tajaouart** [diegoveloper/flutter_percent_indicator#69]
it will be a great idea if the progress bar supports an onComplete function !!

**Comment by diegoveloper** [comment]
hmm is not difficult to add that feature, I don't have much time this month, you could send a pull request if you want :)

**Comment by diegoveloper** [comment]
Thanks @br-programmer to add this feature,  @tajaouart check the version `2.1.6` , now you can add a callback `onAnimationEnd` to know when the animation was completed. Update your `pubspec.yaml` , run `flutter pub upgrade` and try again!
