### ISSUE TITLE
Two LinearPercentIndicator with animation not updating progress bar animation

### ISSUE THREAD

**Issue by litzbalane2017** [diegoveloper/flutter_percent_indicator#7]
Good Day.

I noticed that when using at least two instances of LinearPercentIndicator with animation, the progress bar will always animate with the original values. Even if I use a new percent values after calling setState, They will both animate with the original percent values as before. 

However, If there is no animation, the progress bar updates accordingly.

Thank you.

**Comment by litzbalane2017** [comment]
> Hello, what version are you using?

I was using the latest version 1.0.9. 

> Could you try using the git url directly?

Yes, after trying it using git url. Animation is now working with no more issues with new percent values.

**Comment by diegoveloper** [comment]
Nice, It was an issue solved by a contributor, I need to push these changes to the pub packages. I'll try to do these days and I'll close the issue then. Thanks

**Comment by diegoveloper** [comment]
the package was updated to 1.0.10 .

**Comment by tiagosito** [comment]
Need to update the version number here on the **README.md** page, is still in the old version
```
dependencies:
  percent_indicator: "^ 1.0.9"
```

**Comment by diegoveloper** [comment]
done! , Thanks @tiagosito
