### ISSUE TITLE
No named parameter with the name 'overflow'

### ISSUE THREAD

**Issue by shofi-ishraak** [diegoveloper/flutter_percent_indicator#79]
../../../.pub-cache/hosted/pub.dartlang.org/percent_indicator-2.1.7+1/lib/linear_percent_indicator.dart:215:9: Error: No named parameter with the name 'overflow'.
        overflow: Overflow.visible,
        ^^^^^^^^
../../../flutter/packages/flutter/lib/src/widgets/basic.dart:3273:3: Context: Found this candidate, but the arguments don't match.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.23.0-4.0.pre, on Mac OS X 10.15.6 19G2021 x86_64,
    locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.1)
[✓] Connected device (3 available)

**Comment by diegoveloper** [comment]
If it doesn't work on dev, try using an older version

**Comment by shofi-ishraak** [comment]
flutter team already suggested solutions !
https://github.com/flutter/flutter/issues/66135 
Very soon this changes will be on stable and beta ! if fix is simple and doesn't  break stable channel, then we should get this fix for flutter_percent_indicator !

**Comment by diegoveloper** [comment]
ok, nice catch, I'll update the package today, thanks

**Comment by diegoveloper** [comment]
Package updated, check `2.1.7+2`

**Comment by shofi-ishraak** [comment]
Thanks ..  issue solved !
