### ISSUE TITLE
widgetIndicator size seems to be hardcoded

### ISSUE THREAD

**Issue by amigax** [diegoveloper/flutter_percent_indicator#87]
Im trying to adjust the widgetIndicator like this:

`  Image.asset
        (
        "assets/butt.png",
        width: 5,
        height: 5,
      `),``

But all values have no effect, is it hardcoded? Id like to be able to resize this, thanks!!

**Comment by diegoveloper** [comment]
Add a sample code to reproduce the issue. An screenshot if it's possible
too . thanks

**Comment by amigax** [comment]
`CircularPercentIndicator makeCircularDialInMiddle(double width)
  {
    return CircularPercentIndicator
      (
      radius: width/1.6,
      lineWidth: 30.0,
      animation: true,
      animationDuration: 1000,
      percent: 0.25,
      widgetIndicator:
      Image.asset
        (
        "assets/butt.png",
        width: 5, //ADJUST HERE DOESNT DO ANYTHING
        height: 5,
      ),
      center:
      //the stuff in the middle of the circle
      Column
        (
        crossAxisAlignment: CrossAxisAlignment.center,
        children:
        [
          Spacer(),
          Text
            (
            "DISPONIBLE",
            style: TextStyle
              (
                fontSize: 10.0,
                fontWeight: FontWeight.bold,
                color: Prefs.green
            ),
          ),
          Text
            (
            "600€",
            style: TextStyle
              (
                fontSize: 24.0,
                fontWeight: FontWeight.bold,
                color: Prefs.grey
            ),
          ),
          Image.asset
            (
            "assets/arrows.png",
            width: width/20,
          ),
          Text
            (
            "120€",
            style: TextStyle
              (
                fontSize: 30.0,
                fontWeight: FontWeight.bold,
                color: Prefs.green
            ),
          ),
          Spacer(),
        ],
      ),
      animateFromLastPercent: true,
      circularStrokeCap: CircularStrokeCap.round,
      progressColor: Prefs.green,
      backgroundColor: Prefs.lightGrey,
    );
  }`

**Comment by diegoveloper** [comment]
Add a `Center` widget as a parent of your Image widget.

**Comment by amigax** [comment]
AWESOME! it works, thanks a lot, great widget btw. Cheers.
