### ISSUE TITLE
RadialGradient?

### ISSUE THREAD

**Issue by welfvh** [diegoveloper/flutter_percent_indicator#88]
Can we please get the option to set a radial gradient instead of a linear one?

**Comment by diegoveloper** [comment]
sorry for the late response, what do you want to achieve?

**Comment by welfvh** [comment]
see the logo at potential.app -- this is the look that I'd love to replicate in the app!

**Comment by diegoveloper** [comment]
it would be great if you can paste the image here.

**Comment by welfvh** [comment]
![logo512](https://user-images.githubusercontent.com/36489530/101076515-64117200-359b-11eb-8307-fcfa97cd7605.png)

**Comment by diegoveloper** [comment]
not sure if that's a radialgradient, it's more similar to https://api.flutter.dev/flutter/painting/SweepGradient-class.html  , anyways , pull request are open
