### ISSUE TITLE
How LinearPercentIndicator auto width

### ISSUE THREAD

**Issue by joelcho** [diegoveloper/flutter_percent_indicator#9]
I want the length (width) of the progress bar to be the same as the width of the current parent widget, but I can't do this because 'width' is @required.

How can I do that?

Forgive me for being a recruit.

**Comment by diegoveloper** [comment]
You will have to get the size of your parent first, after that rebuild the widget:

https://medium.com/@diegoveloper/flutter-widget-size-and-position-b0a9ffed9407
