### ISSUE TITLE
Widget indicator is slightly off

### ISSUE THREAD

**Issue by amigax** [diegoveloper/flutter_percent_indicator#92]
When at 0% or 100% you can see the widget indicator is not exactly in the expected position (0 degrees), it looks like it is at say 5 degrees,

**Comment by yfer** [comment]
I got the same situation. Seems like lineWidth affecting where on the circle sector progress starts and ends.

**Comment by diegoveloper** [comment]
Please add a minimum sample code to reproduce the issue.

**Comment by yfer** [comment]
```
new CircularPercentIndicator(
                  radius: 100.0,
                  lineWidth: 40.0, // HERE
                  percent: 0.5,
                  center: new Text("100%"),
                  progressColor: Colors.green,
                )
```

Ark that displayed are not starting at PI/2 angle, it is off. The more lineWidth - the more off it is.

**Comment by diegoveloper** [comment]
Hmm what do you mean, I see the text at the center.

![Simulator Screen Shot - iPhone 8 - 2020-12-16 at 10 41 36](https://user-images.githubusercontent.com/4898256/102370636-4bd22780-3f8b-11eb-93d0-d2d7fdcc1aee.png)

**Comment by yfer** [comment]
Exactly. But nobody talking about text. You clearly can see on you screenshot that the progress indicator is off. On your 50% example it is not on starting on pi/2 and ending on 3pi/2.

**Comment by diegoveloper** [comment]
yeah, because the radius is limited to 100

**Comment by yfer** [comment]
Not sure how this is related as we are talking about arc segment.  
I certainly understand how and why this is implemented. It seems like paint stroke.width Is messing with this.
It is just as a user I would expect more predictable behaviour.

**Comment by diegoveloper** [comment]
sure, pull request are open and welcome
