### ISSUE TITLE
LinearGradient for LinearPercentIndicator

### ISSUE THREAD

**Issue by vientn1998** [diegoveloper/flutter_percent_indicator#95]
I have set gradient color for LinearPercentIndicator but it's not success. Does LinearPercentIndicator not support set gradient?
Plz help me. Thanks you.
<img width="962" alt="Screen Shot 2020-12-15 at 23 16 09" src="https://user-images.githubusercontent.com/42715186/102241541-ab98e600-3f2b-11eb-82d0-1848ac78e724.png">

**Comment by diegoveloper** [comment]
You can only use `progressColor` or `linearGradient` but not both at the same time.

**Comment by vientn1998** [comment]
> You can only use `progressColor` or `linearGradient` but not both at the same time.

I tried and it's succeeded. 
Thanks you so much <3.
