### ISSUE TITLE
How to stop animation when I was started animation before in LinearPercentIndicator.

### ISSUE THREAD

**Issue by vientn1998** [diegoveloper/flutter_percent_indicator#97]
Hi @diegoveloper,
I want stop animation but still keep current value in LinearPercentIndicator. I have check conditions to stop, but it's not still working.
![Screen Shot 2020-12-16 at 16 22 51](https://user-images.githubusercontent.com/42715186/102330144-c7e46380-3fbb-11eb-9433-4c1a57840afd.png)

**Comment by diegoveloper** [comment]
Hey I added some changes into master, could you try pointing directly to my repo in your `pubspec.yam` ?, notice that you can't reactive the animation since this widget wasn't designed for this behavior.  Anyways Pull requests are welcome.

In `master` the `SampleLinearPage` is updated.
