### ISSUE TITLE
Proper Arc for Circular Percent Indicator

### ISSUE THREAD

**Issue by Vivek0004** [diegoveloper/flutter_percent_indicator#98]
# Circular Progress Indicator

In Circular Percent Indicator, there is a property to set arc but in **HALF** arc the circle also appears if we gave a background color and that's also feels like a border to the Arc but there is a full circle behind that half arc, i have made a few changes and it appears to be in like that in the image

I hope you also like this
and if you are interested i can make a PR

Hoping for a soon reply
[
![Half Arc with a border](https://user-images.githubusercontent.com/56130227/102640826-1131e000-4181-11eb-9939-68c863db9f40.jpg) 
](url)

**Comment by diegoveloper** [comment]
great a PR will be welcome.
